version: '2.4'
services:
  production:
    image: "documentation"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '127.0.0.1:8080:80'
    read_only: false
    tmpfs:
      - /tmp
    restart: unless-stopped