nav:
  - Home: index.md
  # - Page not migrated: not-found.md
  # - Bookstack: bookstack.md
  - Automation:
      - Ansible:
          - Ansible basics: automation/ansible/basics.md
          - Ansible install python: automation/ansible/python-install.md
      - Airflow basics: automation/airflow/airflow-basics.md
  - Cloud:
      - Terraform:
          - Building Infrastructure in terraform: cloud/terraform/building-infrastructure.md
          - Openstack error: cloud/terraform/openstack.md
          - "Terraform plugin Cannot locate module locally, unknown reason": cloud/terraform/terraform-plugin-cannot-locate-module-locally-unknown-reason.md
          - Google IAP: cloud/terraform/google-iap.md
          - tfupdate: cloud/terraform/tfupdate.md
          - "Recursive delete of .terraform": cloud/terraform/recursive-delete-of-terraform.md
          - Remote Data: cloud/terraform/remote-data.md
          - To string from list in terraform: cloud/terraform/to-string-from-list.md
      - Google Cloud:
          - Curl to IAP: cloud/gcp/curl-to-iap.md
          - Export to terraform using gcloud cli:  cloud/gcp/export-to-terraform-using-gcloud-cli.md
          - Grafeas: cloud/gcp/grafeas.md
      - Aqua:
          - Aqua Page 1: cloud/aqua/aqua-page-1.md
          - Aqua Page 2: cloud/aqua/aqua-page-2.md
          - Aqua partnership notes: cloud/aqua/partnership-info.md
  - Certifications:
      - Google Cloud Architect:
          - Google architect - Page 1: certifications/google-certs/gcp-architect/gcp-architect-1.md
          - Google architect - Page 2: certifications/google-certs/gcp-architect/gcp-architect-2.md
          - Google architect - Page 3: certifications/google-certs/gcp-architect/gcp-architect-3.md
          - Kubectl commands: certifications/google-certs/gcp-architect/kubectl-commands.md
          - GCP Load balancer: certifications/google-certs/gcp-architect/gcp-load-balancer.md
      - Google Security:
          - Google Security - Exam topics : certifications/google-certs/gcp-security/1-the-exam-topic.md
          - Google Security - Page 1: certifications/google-certs/gcp-security/gcp-security-1.md
      - Gsuit administration:
          - Gsuit User administration: certifications/google-certs/workspace-admin/user-administration.md
          - Managing Gsuit: certifications/google-certs/workspace-admin/managing-gsuit.md
          - Google MDM: certifications/google-certs/workspace-admin/mdm.md
      - GCP Associate:
          - Regions and Zones: certifications/google-certs/gcp-associate/regions-and-zones.md
          - Associate cert exam: certifications/google-certs/gcp-associate/gcp.md
          - Google Compute engine: certifications/google-certs/gcp-associate/gce-google-compute-engine.md
          - Networking and LB: certifications/google-certs/gcp-associate/networking-and-lb.md
          - VM Bootstrapping, templates and Images: certifications/google-certs/gcp-associate/vm-bootstrapping-templates-and-images.md
          - Costs: certifications/google-certs/gcp-associate/costs.md
          - Compute Engine: certifications/google-certs/gcp-associate/compute-engine.md

      - CKA:
          - CKA - Page 1: certifications/cka/cka-1.md
  - KB Articles:
      - Disk management:
        - Expanding a file system: kb/disk-management/expanding-a-filesystem.md
        - Formatting drive and Auto mount: kb/disk-management/formatting-drive-automount.md
        - Mount a new drive: kb/disk-management/mount-a-new-drive.md
        - "GPT PMBR Size Mismatch will be corrected by w(rite)" : kb/disk-management/gpt-pmbr-size-mismatch-will-be-corrected-by-write.md
      - Minio:
          - OLD : kb/minio/old.md
          - Connecting to minio over s3fs: kb/minio/minio-over-s3fs.md
          - creating users and assigning policies: kb/minio/s3-policies.md
      - PHP:
          - Install PHP: kb/php/install-php.md
          - Wordpress permissions: kb/php/wordpress-permissions.md
      - Docker:
          - Installing Docker: kb/docker/installing-docker.md
          - Basics of docker: kb/docker/basics-of-docker.md
          - Installing jellyfin: kb/docker/installing-jellyfin.md
          - "Docker: Intro and notes": kb/docker/docker-intro-and-notes.md
          - Exporting and importing: kb/docker/exporting-and-importing.md
          - Docker Architecture: kb/docker/docker-architecture.md
          - Bulk retag: kb/docker/bulk-retag.md
          - Copy images between repositories: kb/docker/copy-containers-between-repos.md
      - Google cloud:
          - "Projects, Resources, IAM Users, Roles, Permissions, APIs, and Cloud Shell" : kb/google-cloud/projects-resources-iam-users-roles-permissions-apis-and-cloud-shell.md
          - "Serverless VPC access for Cloudrun across Projects" : kb/google-cloud/serverless-vpc-access-for-cloudrun-across-projects.md
          - Get project using GCE Metadata API: kb/google-cloud/api-get-project.md
          - Get serviceAccount using GCE Metadata API: kb/google-cloud/api-get-sa.md
      - Linux Networking:
          - Uninstall Netplan: kb/linux-networking/uninstall-netplan.md
          - DNS on Ubuntu: kb/linux-networking/dns-on-ubuntu.md
          - Bringing up Interfaces: kb/linux-networking/bringing-up-interfaces.md
          - Netplan 2 interfaces: kb/linux-networking/netplan-2-interfaces.md
          - Centos Iptables: kb/linux-networking/centos-iptables.md
          - Null routing: kb/linux-networking/null-routing.md
          - Listen on a port: kb/linux-networking/listen-on-a-port.md
          - "List of unique IP's": kb/linux-networking/list-of-unique-ips.md
          - Connections on a port: kb/linux-networking/connections-on-a-port.md
          - RVC IP Range: kb/linux-networking/rvc-ip-range.md
          - Nmap scanning: kb/linux-networking/nmap-scans.md
      - SSH:
          - SSH Keys: kb/ssh/ssh-keys.md
          - SSH Port redirection: kb/ssh/ssh-port-redirection.md
          - SSH client setup using keys: kb/ssh/ssh-client-setup-using-keys.md
          - Importing SSH keys from GitHUb: kb/ssh/importing-ssh-keys-from-github.md
          - Weird Bash: kb/ssh/weird-bash.md
          - sshuttle: kb/ssh/sshuttle.md
      - Public web Facing:
          - Cachet: kb/public-web-facing/cachet.md
          - Certbot: kb/public-web-facing/certbot.md
          - Reverse web proxy: kb/public-web-facing/reverse-web-proxy.md
          - Bookstack: kb/public-web-facing/bookstack.md
          - Jellyfin S3: kb/public-web-facing/jellyfin-s3.md
          - Custom Headers: kb/public-web-facing/custom-headers.md
          - Remove server headers: kb/public-web-facing/remove-server-headers.md
          - Wildcart Certificates: kb/public-web-facing/wildcard-certificates.md
          - Send test email on passbolt: kb/public-web-facing/send-test-email-on-passbolt.md
          - Check passbolt is Healthy: kb/public-web-facing/check-passbolt-is-healthy.md
          - "nginx.service failed because the control process exited": kb/public-web-facing/nginxservice-failed-because-the-control-process-exited.md
          - Serving breadNET when server is offline:  kb/other/downloading-the-breadnet-site-and-serving-a-stale-copy.md
      - Wasabi:
          - Policies: kb/wasabi/policies.md
          - Transport endpoint is not connected: kb/wasabi/transport-endpoint-is-not-connected.md
      - Authentication:
          - Fingerprint on Linux Mint: kb/authentication/fingerprint-on-linux-mint.md
      - AWS:
          - AWS Cloud-init: kb/aws/cloud-init-sg1.md
          - AWS CLI: kb/aws/aws-cli.md
      - Google Workspace:
          - Setup Routing: kb/google-workspace/setup-routing.md
      - Linux Command line:
          - uuidgen Lower case: kb/linux-cli/uuidgen-lowercase.md
          - Broken link checker: kb/linux-cli/blc.md
          - Get current Folder: kb/linux-cli/get-current-folder.md
          - "xcrun: error: invalid active developer path": kb/linux-cli/xcrun-error-invalid-active-developer-path.md
      - Networking:
          - VPN Network routing Mikrotik: kb/networking/vpn-network-routing-mikrotik.md
          - Updating Ubiquiti Tough switch: kb/networking/update-tough-switch.md
      - Cloud:
          - cloud-init: kb/cloud/cloud-init.md
      - Markdown:
          - How to use git: kb/markdown/github-repos-and-stuff.md
          - Custom markdown badges: kb/markdown/custom-badges.md
          - Built By badge: kb/markdown/built-by-badge.md


      - Helm:
          - Create a helm chart: kb/helm/create-helm-chart.md
          - Push chart to Artifact Registry: kb/helm/push-chart-to-ar.md
          - Use GCS as helm repo: kb/helm/helm-repo-gcs.md
  - Kubernetes:
      - kubernetes/index.md
      - KB:
          - kubernetes/kb/index.md
          - Connect to container that has side car containers: kubernetes/kb/connect-to-container-that-has-sidecars.md
          - Delete not running pods: kubernetes/kb/deleting-not-running-pods.md
          - Set default namespace kubectl: kubernetes/kb/kubectl-set-namespace.md
          - Testing RBAC: kubernetes/kb/rbac-testing.md
          - Sleeper pod: kubernetes/kb/sleeper.md
          - Downward API: kubernetes/kb/downward-api.md
      - GKE:
          - kubernetes/gke/index.md
          - Workload ID KSA: kubernetes/gke/service-account-with-workload-id.md
          - Workload ID test pod: kubernetes/gke/workload-id-test.md
      - K3S:
          - kubernetes/k3s/index.md
  - Home:
      - home/index.md
      - Consumer Unit: home/cu/consumer-unit.md
      - Oven : home/oven/oven.md
      - Washing Machine: home/washing/washing-machine.md




repo_name: docu
repo_url: https://github.com/userbradley/documentation.breadnet.co.uk
edit_uri: edit/dev/docs/
site_name: !ENV [env,"breadNET Documentation"]
site_url: !ENV [domain, "https://documentation.breadnet.co.uk"]
site_description: breadNET Public Documentation

#extra_css:
#  - stylesheets/custom.css # Custom header color

theme:
  name: material
  favicon: https://breadnet.co.uk/favicon.ico
  logo: https://breadnet.co.uk/favicon.png
  custom_dir: overrides
  icon:
    repo: fontawesome/brands/github-alt
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

  palette:
    - scheme: default
      primary: !ENV [color, ""]
      accent: !ENV [color, ""]
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: !ENV [color, ""]
      accent: !ENV [color, ""]
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.instant # IDK
    - navigation.tracking #Anchor links
    - !ENV [nav, ""]#navigation.expand #Exapnds the navigation in the UI, disabled by default, but enabled in dev
    - content.code.annotate
    - search.share
    # - search.highlight
    - navigation.top # back to top of page
    - navigation.indexes



markdown_extensions:
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - md_in_html
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true # Pretty check lists
  - tables
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  #- social # Needs to be built in to the docker image which I dont care for
#- git-revision-date-localized:
#    type: iso_datetime
#    enable_creation_date: true ## Needs this built in to the docker image which I don't care for


extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://uk.linkedin.com/in/bradley-stannard
      name: My Linkedin
    - icon: fontawesome/brands/github-alt
      link: https://github.com/userbradley
      name: My Github
    - icon: fontawesome/solid/paper-plane
      link: mailto:webmaster@breadnet.co.uk
    - icon: fontawesome/solid/file-lines #https://fontawesome.com/docs/web/setup/upgrade/whats-changed#icons-renamed-in-version-6
      link: https://breadnet.co.uk
      name: My Website
  generator: false
