nav:
  - Home: index.md
  # - Page not migrated: not-found.md
  # - Bookstack: bookstack.md
  - Automation:
      - Ansible:
          - Ansible basics: automation/ansible/basics.md
          - Ansible install python: automation/ansible/python-install.md
      - Airflow basics: automation/airflow/airflow-basics.md
  - Cloud:
      - Aqua:
          - Aqua Page 1: cloud/aqua/aqua-page-1.md
          - Aqua Page 2: cloud/aqua/aqua-page-2.md
          - Aqua partnership notes: cloud/aqua/partnership-info.md
      - AWS:
          - AWS Cloud-init: cloud/aws/cloud-init-sg1.md
          - AWS CLI: cloud/aws/aws-cli.md
      - Digital Ocean:
          - Get list of Digital ocean images: cloud/digitalocean/digitalocean-get-list-of-images.md
      - Fly:
          - cloud/fly/index.md
          - Fly regions and scaling: cloud/fly/fly-regions.md
          - Fly.io in CI: cloud/fly/fly-ci.md
          - Fly Deployment strategy: cloud/fly/deployment-strategy.md
          - Authenticate to Fly docker Registry: cloud/fly/fly-docker-auth.md
          - Get the Real IP address from fly when behind cloudflare: cloud/fly/fly-real-ip.md
      - Google Cloud:
          - Get project using GCE Metadata API: cloud/gcp/api-get-project.md
          - Get serviceAccount using GCE Metadata API: cloud/gcp/api-get-sa.md
          - "Curl to GCR/ AR": cloud/gcp/curl-gcr-ar.md
          - Curl to IAP: cloud/gcp/curl-to-iap.md
          - Export to terraform using gcloud cli:  cloud/gcp/export-to-terraform-using-gcloud-cli.md
          - Filter fields from gcloud putput: cloud/gcp/filter-gcloud-output.md
          - Forward real IP to a NGINX behind a GCP Load Balancer: cloud/gcp/forward-real-ip-to-a-nginx-behind-a-gcp-load-balancer.md
          - Get project name of GCS bucket: cloud/gcp/get-project-name-of-gcs-bucket.md
          - Grafeas: cloud/gcp/grafeas.md
          - "Projects, Resources, IAM Users, Roles, Permissions, APIs, and Cloud Shell": cloud/gcp/projects-resources-iam-users-roles-permissions-apis-and-cloud-shell.md
          - "Serverless VPC access for Cloudrun across Projects": cloud/gcp/serverless-vpc-access-for-cloudrun-across-projects.md
          - SSH using IAP: cloud/gcp/ssh-iap.md
          - SSHuttle using Google IAP: cloud/gcp/sshuttle-using-google-iap.md
          - Useful gcloud commands: cloud/gcp/useful-gcloud-commands.md
      - Terraform:
          - Building Infrastructure in terraform: cloud/terraform/building-infrastructure.md
          - Bulk delete from terraform state: cloud/terraform/bulk-delete-terraform-state.md
          - "Failed to get existing workspaces: querying Cloud Storage failed: storage: bucket doesn't exist": cloud/terraform/failed-to-get-existing-workspaces-querying-Cloud-Storage-failed-storage-bucket-doesnt-exist.md
          - Google IAP: cloud/terraform/google-iap.md
          - Openstack error: cloud/terraform/openstack.md
          - "Recursive delete of .terraform": cloud/terraform/recursive-delete-of-terraform.md
          - Remote Data: cloud/terraform/remote-data.md
          - Terraform lock file update: cloud/terraform/terraform-lock-file-update.md
          - "Terraform plugin Cannot locate module locally, unknown reason": cloud/terraform/terraform-plugin-cannot-locate-module-locally-unknown-reason.md
          - tfupdate: cloud/terraform/tfupdate.md
          - To string from list in terraform: cloud/terraform/to-string-from-list.md
  - Certifications:
      - Google Cloud Architect:
          - Google architect - Page 1: certifications/google-certs/gcp-architect/gcp-architect-1.md
          - Google architect - Page 2: certifications/google-certs/gcp-architect/gcp-architect-2.md
          - Google architect - Page 3: certifications/google-certs/gcp-architect/gcp-architect-3.md
          - Kubectl commands: certifications/google-certs/gcp-architect/kubectl-commands.md
          - GCP Load balancer: certifications/google-certs/gcp-architect/gcp-load-balancer.md
      - Google Security:
          - Google Security - Exam topics : certifications/google-certs/gcp-security/1-the-exam-topic.md
          - Google Security - Page 1: certifications/google-certs/gcp-security/gcp-security-1.md
      - Gsuit administration:
          - Gsuit User administration: certifications/google-certs/workspace-admin/user-administration.md
          - Managing Gsuit: certifications/google-certs/workspace-admin/managing-gsuit.md
          - Google MDM: certifications/google-certs/workspace-admin/mdm.md
      - GCP Associate:
          - Regions and Zones: certifications/google-certs/gcp-associate/regions-and-zones.md
          - Associate cert exam: certifications/google-certs/gcp-associate/gcp.md
          - Google Compute engine: certifications/google-certs/gcp-associate/gce-google-compute-engine.md
          - Networking and LB: certifications/google-certs/gcp-associate/networking-and-lb.md
          - VM Bootstrapping, templates and Images: certifications/google-certs/gcp-associate/vm-bootstrapping-templates-and-images.md
          - Costs: certifications/google-certs/gcp-associate/costs.md
          - Compute Engine: certifications/google-certs/gcp-associate/compute-engine.md

      - CKA:
          - CKA - Page 1: certifications/cka/cka-1.md
  - KB Articles:
      - Disk management:
        - Expanding a file system: kb/disk-management/expanding-a-filesystem.md
        - Formatting drive and Auto mount: kb/disk-management/formatting-drive-automount.md
        - Mount a new drive: kb/disk-management/mount-a-new-drive.md
        - "GPT PMBR Size Mismatch will be corrected by w(rite)" : kb/disk-management/gpt-pmbr-size-mismatch-will-be-corrected-by-write.md
      - Minio:
          - OLD : kb/minio/old.md
          - Connecting to minio over s3fs: kb/minio/minio-over-s3fs.md
          - creating users and assigning policies: kb/minio/s3-policies.md
      - PHP:
          - Install PHP: kb/php/install-php.md
          - Wordpress permissions: kb/php/wordpress-permissions.md
      - Docker:
          - Installing Docker: kb/docker/installing-docker.md
          - Basics of docker: kb/docker/basics-of-docker.md
          - Installing jellyfin: kb/docker/installing-jellyfin.md
          - "Docker: Intro and notes": kb/docker/docker-intro-and-notes.md
          - Exporting and importing: kb/docker/exporting-and-importing.md
          - Docker Architecture: kb/docker/docker-architecture.md
          - Bulk retag: kb/docker/bulk-retag.md
          - Copy images between repositories: kb/docker/copy-containers-between-repos.md
      - Git:
          - Git with different SSH keys: kb/git/git-with-different-ssh-keys.md
          - Migrate repo to Monorepo: kb/git/migrate-repo-to-mono-repo.md
          - Set git username and email per repo: kb/git/set-git-user-per-repo.md
      - Linux Networking:
          - Bringing up Interfaces: kb/linux-networking/bringing-up-interfaces.md
          - Centos Iptables: kb/linux-networking/centos-iptables.md
          - Connections on a port: kb/linux-networking/connections-on-a-port.md
          - DNS on Ubuntu: kb/linux-networking/dns-on-ubuntu.md
          - "List of unique IP's": kb/linux-networking/list-of-unique-ips.md
          - Listen on a port: kb/linux-networking/listen-on-a-port.md
          - Netplan 2 interfaces: kb/linux-networking/netplan-2-interfaces.md
          - Netplan Set static IP: kb/linux-networking/netplan-static-ip.md
          - Nmap scanning: kb/linux-networking/nmap-scans.md
          - Null routing: kb/linux-networking/null-routing.md
          - RVC IP Range: kb/linux-networking/rvc-ip-range.md
          - Uninstall Netplan: kb/linux-networking/uninstall-netplan.md
      - SSH:
          - SSH Keys: kb/ssh/ssh-keys.md
          - SSH Port redirection: kb/ssh/ssh-port-redirection.md
          - SSH client setup using keys: kb/ssh/ssh-client-setup-using-keys.md
          - Importing SSH keys from GitHUb: kb/ssh/importing-ssh-keys-from-github.md
          - Weird Bash: kb/ssh/weird-bash.md
          - sshuttle: kb/ssh/sshuttle.md
      - Nginx:
          - Reverse web proxy: kb/nginx/reverse-web-proxy.md
          - Custom Headers: kb/nginx/custom-headers.md
          - Remove server headers: kb/nginx/remove-server-headers.md
          - nginx.service failed because the control process exited: kb/nginx/nginxservice-failed-because-the-control-process-exited.md
          - nginx redirects to the first alphabetical site when not found in config: kb/nginx/nginx-redirects-to-the-first-alphabetical-site-when-not-found-in-config.md

      - Public web Facing:
          - Bookstack: kb/public-web-facing/bookstack.md
          - Cachet: kb/public-web-facing/cachet.md
          - Certbot: kb/public-web-facing/certbot.md
          - Check passbolt is Healthy: kb/public-web-facing/check-passbolt-is-healthy.md
          - Serving breadNET when server is offline:  kb/public-web-facing/downloading-the-breadnet-site-and-serving-a-stale-copy.md
          - Jellyfin S3: kb/public-web-facing/jellyfin-s3.md
          - Send test email on passbolt: kb/public-web-facing/send-test-email-on-passbolt.md
          - Wildcard Certificates: kb/public-web-facing/wildcard-certificates.md
          - Change password using WPCli: kb/public-web-facing/wp-cli-password.md
      - Wasabi:
          - Policies: kb/wasabi/policies.md
          - Transport endpoint is not connected: kb/wasabi/transport-endpoint-is-not-connected.md
      - Authentication:
          - Fingerprint on Linux Mint: kb/authentication/fingerprint-on-linux-mint.md

      - Google Workspace:
          - Setup Routing: kb/google-workspace/setup-routing.md
      - Linux Command line:
          - Always restart service after failure systemd: kb/linux-cli/always-restart-service-after-failure-systemd.md
          - Backup SQlite Database: kb/linux-cli/backup-sqlite-db.md
          - Broken link checker: kb/linux-cli/blc.md
          - Bulk change file extensions: kb/linux-cli/bulk-change-file-extension.md
          - Passwordless sudo using fingerprint on mac: kb/linux-cli/fingerprint-for-sudo-mac.md
          - Get current Folder: kb/linux-cli/get-current-folder.md
          - "The following signatures couldn't be verified because the public key is not available" : kb/linux-cli/the-following-signatures-couldnt-be-verified-because-the-public-key-is-not-available.md
          - uuidgen Lower case: kb/linux-cli/uuidgen-lowercase.md
          - "xcrun: error: invalid active developer path": kb/linux-cli/xcrun-error-invalid-active-developer-path.md
          - "Your Xcode is too outdated.": kb/linux-cli/your-xcode-is-too-outdated.md
      - Networking:
          - VPN Network routing Mikrotik: kb/networking/vpn-network-routing-mikrotik.md
          - Updating Ubiquiti Tough switch: kb/networking/update-tough-switch.md
      - Cloud init:
          - cloud-init: kb/cloud-init/cloud-init.md
      - Markdown:
          - How to use git: kb/markdown/github-repos-and-stuff.md
          - Custom markdown badges: kb/markdown/custom-badges.md
          - Built By badge: kb/markdown/built-by-badge.md

  - Kubernetes:
      - kubernetes/index.md
      - KB:
          - kubernetes/kb/index.md
          - Connect to container that has side car containers: kubernetes/kb/connect-to-container-that-has-sidecars.md
          - Delete not running pods: kubernetes/kb/deleting-not-running-pods.md
          - Set default namespace kubectl: kubernetes/kb/kubectl-set-namespace.md
          - Testing RBAC: kubernetes/kb/rbac-testing.md
          - Sleeper pod: kubernetes/kb/sleeper.md
          - Downward API: kubernetes/kb/downward-api.md
          - Using ArgoCD Image updater with Google Artifact Registry: kubernetes/kb/using-argocd-image-updater-with-google-artifact-registry.md
      - Helm:
          - Create a helm chart: kubernetes/helm/create-helm-chart.md
          - Push chart to Artifact Registry: kubernetes/helm/push-chart-to-ar.md
          - Use GCS as helm repo: kubernetes/helm/helm-repo-gcs.md
          - Force containers to update when config map changes in helm: kubernetes/helm/force-rollout-on-configmap-update.md
      - GKE:
          - kubernetes/gke/index.md
          - Workload ID KSA: kubernetes/gke/service-account-with-workload-id.md
          - Workload ID test pod: kubernetes/gke/workload-id-test.md
      - K3S:
          - kubernetes/k3s/index.md
          - "Error 1962: No operating system found": kubernetes/k3s/lenovo-sff-ubuntu.md
  - Home:
      - home/index.md
      - Consumer Unit: home/cu/consumer-unit.md
      - Oven : home/oven/oven.md
      - Washing Machine: home/washing/washing-machine.md
      - Hot water heater:
          - Reducing temperature: home/water-heater/reduce-temprature.md




repo_name: documentation
repo_url: https://github.com/userbradley/documentation.breadnet.co.uk
edit_uri: edit/dev/docs/
site_name: !ENV [env,"breadNET Documentation"]
site_url: !ENV [domain, "https://documentation.breadnet.co.uk"]
site_description: breadNET Documentation

#extra_css:
#  - stylesheets/custom.css # Custom header color

theme:
  name: material
  favicon: favicon.ico
  logo: favicon.png
  custom_dir: !ENV [dir, "overrides-prod"]
  icon:
    repo: fontawesome/brands/github-alt
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
     # tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

  palette:
    - scheme: default
      primary: !ENV [color, ""]
      accent: !ENV [color, ""]
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: !ENV [color, ""]
      accent: !ENV [color, ""]
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.instant # IDK
    - navigation.tracking #Anchor links
    #- !ENV [nav, ""]#navigation.expand #Exapnds the navigation in the UI, disabled by default, but enabled in dev
    - content.code.annotate
    - search.share
    # - search.highlight
    - navigation.top # back to top of page
    - navigation.indexes # Allows index.md pages
    - content.tabs.link


markdown_extensions:
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - md_in_html
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true # Pretty check lists
  - tables
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.snippets
  - abbr

plugins:
  - search
  - social
  #- offline

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://uk.linkedin.com/in/bradley-stannard
      name: My Linkedin
    - icon: fontawesome/brands/github-alt
      link: https://github.com/userbradley
      name: My Github
    - icon: fontawesome/solid/paper-plane
      link: mailto:webmaster@breadnet.co.uk
    - icon: fontawesome/solid/file-lines
      link: https://breadnet.co.uk
      name: My Website
  generator: false # I am sorry I will enable it later
