nav:
  - Home: index.md
  - KB Articles:
      - Disk management:
        - Expanding a file system: kb/disk-management/expanding-a-filesystem.md
        - Formatting drive and Auto mount: kb/disk-management/formatting-drive-automount.md
        - Mount a new drive: kb/disk-management/mount-a-new-drive.md
        - "GPT PMBR Size Mismatch will be corrected by w(rite)" : kb/disk-management/gpt-pmbr-size-mismatch-will-be-corrected-by-write.md
      - Minio:
          - OLD : kb/minio/old.md
          - Connecting to minio over s3fs: kb/minio/minio-over-s3fs.md
          - creating users and assigning policies: kb/minio/s3-policies.md
      - PHP:
          - Install PHP: kb/php/install-php.md
          - Wordpress permissions: kb/php/wordpress-permissions.md
      - Docker:
          - Installing Docker: kb/docker/installing-docker.md
          - Basics of docker: kb/docker/basics-of-docker.md
          - Installing jellyfin: kb/docker/installing-jellyfin.md
          - "Docker: Intro and notes": kb/docker/docker-intro-and-notes.md
          - Exporting and importing: kb/docker/exporting-and-importing.md
          - Docker Architecture: kb/docker/docker-architecture.md
          - Bulk retag: kb/docker/bulk-retag.md
      - Linux Networking:
          - Uninstall Netplan: kb/linux-networking/uninstall-netplan.md
      - SSH:
         - SSH Keys: kb/ssh/ssh-keys.md



repo_name: docu
repo_url: https://github.com/userbradley/documentation.breadnet.co.uk
edit_uri: edit/dev/docs/
site_name: !ENV [env,"breadNET Documentation"]
site_url:
site_description: breadNET Public Documentation



theme:
  name: material
  favicon: https://breadnet.co.uk/favicon.ico
  logo: https://breadnet.co.uk/favicon.png
  custom_dir: overrides
  icon:
    repo: fontawesome/brands/github-alt
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

  palette:
    - scheme: default
      primary: !ENV [color, ""]
      accent: !ENV [color, ""]
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: !ENV [color, ""]
      accent: !ENV [color, ""]
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.instant # IDK
    - navigation.tracking #Anchor links
    - !ENV [nav, ""]#navigation.expand #Exapnds the navigation in the UI, disabled by default, but enabled in dev
    - content.code.annotate
    - search.share
    - search.highlight
    - navigation.top # back to top of page



markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - md_in_html
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true # Pretty check lists
  - tables
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
plugins:
#- git-revision-date-localized:
#    type: iso_datetime
#    enable_creation_date: true ## Needs this built in to the docker image which I don't care for


extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://uk.linkedin.com/in/bradley-stannard
      name: My Linkedin
    - icon: fontawesome/brands/github-alt
      link: https://github.com/userbradley
      name: My Github
    - icon: fontawesome/solid/paper-plane
      link: mailto:webmaster@breadnet.co.uk
    - icon: fontawesome/solid/file-lines #https://fontawesome.com/docs/web/setup/upgrade/whats-changed#icons-renamed-in-version-6
      link: https://breadnet.co.uk
      name: My Website
  generator: false