version: 3

tasks:
  serve:
    cmds:
      - mkdocs serve --dirtyreload
  default:
    cmds:
      - mkdocs serve
  build:
    cmds:
      - mkdocs build

  fly:
    silent: true
    cmds:
      - fly deploy --dockerfile dev.Dockerfile --config dev.toml
  fly-prd:
    silent: true
    cmds:
      - fly deploy --dockerfile Dockerfile --config prod.toml