version: 3

tasks:
  serve:
    desc: Runs mkdocs serve
    cmds:
      - mkdocs serve
  dirty:
    desc: Runs mkdocs dirty reload
    cmds:
      - mkdocs serve --dirtyreload
  default:
    desc: Lists the avalible commands
    cmds:
      - task --list-all
  build:
    desc: Builds the site
    cmds:
      - mkdocs build