version: 3

tasks:
  cleanup:
    desc: Removes the old site files
    cmds:
      - cmd: rm -rvf site
        ignore_error: true

  build:
    desc: Builds the documentation
    cmds:
      - task: cleanup
      - mkdocs build
  serve:
    desc: Serves the site using NGINX locally
    cmds:
      - task: build
      - docker run -it -v $(pwd)/nginx.conf:/etc/nginx/conf.d/default.conf -v $(pwd)/site:/var/www/documentation/ -p 8000:80 nginx:latest



