version: "1.0"
stages:
  - "setup"
  - "mkdocs-build"
  - "deploy"

steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "userbradley/documentation.breadnet.co.uk"
    revision: "${{CF_BRANCH}}"
    git: "github"
    stage: "setup"
  set-env:
    title: "Set env vars"
    stage: "setup"
    image: alpine
    when:
      branch:
        only:
          - dev
    commands:
      - export color=red
      - export env="Development Server"
      - cf_export color env

  build_mkdocs:
    title: Build Mkdocs site
    stage: "mkdocs-build"
    image: "squidfunk/mkdocs-material"
    working_directory: "/codefresh/volume/documentation.breadnet.co.uk/"
    cmd:
      - "build"

  transfer-master:
    title: "Master deploy"
    type: "freestyle"
    stage: "deploy"
    image: "ictu/sshpass:latest"
    when:
      branch:
        only:
          - master
    commands:
      - "mkdir /.ssh"
      - "echo ${{codefresh_ssh_key}} | base64 -d > /.ssh/id_rsa"
      - "chmod 600 /.ssh/id_rsa"
      - scp -o "StrictHostKeyChecking no" -i /.ssh/id_rsa -r documentation.breadnet.co.uk/site/* "${{server}}/documentation"

  transfer-dev:
    title: "Dev deploy"
    type: "freestyle"
    stage: "deploy"
    image: "ictu/sshpass:latest"
    when:
      branch:
        only:
          - dev
    commands:
      - "mkdir /.ssh"
      - "echo ${{codefresh_ssh_key}} | base64 -d > /.ssh/id_rsa"
      - "chmod 600 /.ssh/id_rsa"
      - scp -o "StrictHostKeyChecking no" -i /.ssh/id_rsa -r documentation.breadnet.co.uk/site/* "${{server}}/dev-documentation"