version: "1.0"
stages:
  - "clone"
  - "setup"
  - "docker"
  - "deploy"

steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "userbradley/documentation.breadnet.co.uk"
    revision: "${{CF_BRANCH}}"
    git: "github"
    stage: "clone"


  setup:
    type: parallel
    stage: setup
    steps:
      fly-env:
        title: "Fly API Env"
        stage: "setup"
        image: alpine
        commands:
          - export FLY_API_TOKEN=${{FLY_API_TOKEN}}
          - cf_export FLY_API_TOKEN

      set-robots:
        title: "Set Robots.txt on dev"
        stage: "setup"
        image: alpine
        when:
          branch:
            only:
              - dev
        commands:
          - echo "VXNlci1BZ2VudDogKgpEaXNhbGxvdzogLwo=" | base64 -d > /codefresh/volume/documentation.breadnet.co.uk/docs/robots.txt

  dev-flyregistry-build:
    title: "DEV Fly Build"
    type: "build"
    working_directory: "/codefresh/volume/documentation.breadnet.co.uk/"
    image_name: "documentation-dev"
    tag: "${{CF_SHORT_REVISION}}"
    dockerfile: "dev.Dockerfile"
    stage: "docker"
    registry: fly
    when:
      branch:
        only:
          - dev

  prod-flyregistry-build:
    title: "PROD Fly Build"
    type: "build"
    working_directory: "/codefresh/volume/documentation.breadnet.co.uk/"
    image_name: "documentation-prod"
    tag: "${{CF_SHORT_REVISION}}"
    dockerfile: "Dockerfile"
    stage: "docker"
    registry: fly
    when:
      branch:
        only:
          - master

  deploy-dev:
    title: "DEV Fly Deployment"
    stage: "deploy"
    image: "userbradley/flyctl:latest"
    working_directory: "/codefresh/volume/documentation.breadnet.co.uk/"
    commands:
      - flyctl deploy --config dev.toml --image registry.fly.io/documentation-dev:${{CF_SHORT_REVISION}} --detach
    when:
      branch:
        only:
          - dev


  deploy-prod:
    title: "PROD Fly Deployment"
    stage: "deploy"
    image: "userbradley/flyctl:latest"
    working_directory: "/codefresh/volume/documentation.breadnet.co.uk/"
    commands:
      - flyctl deploy --config prod.toml --image registry.fly.io/documentation-prod:${{CF_SHORT_REVISION}} --detach
    when:
      branch:
        only:
          - master