name: Dev
on:
  push:
    branches:
      - dev
    paths-ignore:
      - .github/workflows/prod.yaml
      - .github/workflows/truffle-hog.yaml
      - .github/dependabot.yml
      - prod.toml
      - Dockerfile
      - overrides-prod/**

jobs:
  site:
    runs-on: ubuntu-latest
    name: Build Documentation
    steps:
      - name: Git Clone
        uses: actions/checkout@v3
      - name: Fly Build and Deploy
        uses: userbradley/actions-fly@v1.0.0
        with:
          flyToken: ${{ secrets.FLY_ACCESS_TOKEN_DEV }}
          configFile: "dev.toml"
          dockerfileName: "dev.Dockerfile"

