name: Dev
on:
  push:
    branches:
      - dev
    paths-ignore:
      - .github/workflows/prod.yaml
      - .github/workflows/truffle-hog.yaml
      - .github/dependabot.yml
      - prod.toml
      - Dockerfile
      - overrides-prod/**

jobs:
  site:
    runs-on: ubuntu-latest
    name: Build Documentation
    steps:
      - name: Git Clone
        uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Login to Fly Registry
        uses: docker/login-action@v2
        with:
          registry: registry.fly.io
          username: x
          password: ${{ secrets.FLY_ACCESS_TOKEN_DEV }}
      - name: Deploy to Fly
        run: flyctl deploy --config dev.toml --dockerfile dev.Dockerfile --local-only --push --detach --auto-confirm
        env:
          FLY_ACCESS_TOKEN: ${{ secrets.FLY_ACCESS_TOKEN_DEV }}