name: Production
on:
  push:
    branches:
      - main
    paths-ignore:
      - .github/workflows/dev.yaml
      - cd/codefresh.yml
      - dev.toml
      - dev.Dockerfile
      - overrides-dev/**


jobs:
  site:
    runs-on: ubuntu-latest
    name: Build Documentation
    steps:
      - name: Git Clone
        uses: actions/checkout@v3
      - name: Fly Build and Deploy
        uses: userbradley/actions-fly@v1.0.0
        with:
          flyToken: ${{ secrets.FLY_ACCESS_TOKEN_PROD }}
